version: '3.8'

services:
  backend:
    container_name: Employee-application
    build: ./Backend
    ports:
      - "3696:3696"
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=admin321
      - PGDATABASE=job_applications_db
      - PGPORT=5432
    volumes:
      - ./uploads:/app/Uploads
    networks:
      - app-network

  employee-application:
    container_name: Employee-application01
    build: ./Employee-application
    ports:
      - "8078:80"
    depends_on:
      - backend
    networks:
      - app-network

  hr-application:
    container_name: HR-application
    build: ./HR-application
    ports:
      - "8079:80"
    depends_on:
      - backend
    networks:
      - app-network

  view-offer:
    container_name: View-offer
    build: ./View-offer
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    container_name: postgres001
    image: postgres:13
    ports:
      - "5116:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: job_applications_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
